### ISSUE TITLE
Install is broken

### ISSUE THREAD

**Issue by ae-foster** [ae-foster/rdbgenerate#1]
When installing this package from pip:

```Collecting rdbgenerate
  Using cached rdbgenerate-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ws/bkccz7pd6qz2t70j2k3yj3jc0000gn/T/pip-build-9KIwkk/rdbgenerate/setup.py", line 14, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 884, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/ws/bkccz7pd6qz2t70j2k3yj3jc0000gn/T/pip-build-9KIwkk/rdbgenerate/README.md'```

**Comment by ae-foster** [comment]
Adding `MANIFEST.in` https://github.com/ae-foster/rdbgenerate/commit/4e4eaf9c58d42ac5c587cebb01ea76b2627576c7 did the trick
